### PR TITLE
First set of change containing telemetry infrastructure for NTVS

### PR DESCRIPTION
**Pull request by nareshjo**
First set of change containing telemetry infrastructure and logging of some datapoints.

This provides infrastructure for for adding concrete implementations for telemetry logger which will implement ITelemetryFactory.

@ryan-dawson @mousetraps

### CODE REVIEW

**Comment by mousetraps** [comment]
Why is this PR not on the Microsoft/nodejstools repo?

Sent from my Rotary Phone

On Aug 5, 2015, at 12:52 AM, Naresh Joshi <notifications@github.com<mailto:notifications@github.com>> wrote:


First set of change containing telemetry infrastructure and logging of some datapoints.

This provides infrastructure for for adding concrete implementations for telemetry logger which will implement ITelemetryFactory.

@ryan-dawson<https://github.com/ryan-dawson> @mousetraps<https://github.com/mousetraps>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/ryan-dawson/nodejstools/pull/1

Commit Summary

  *   First set of change containing telemetry infrastructure and logging of some datapoints.

File Changes

  *   M Common/Product/SharedProject/ProjectNode.cs<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-0> (14)
  *   M Nodejs/NodejsTools.sln<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-1> (8)
  *   M Nodejs/Prerequisites/DisableSkipVerification.reg<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-2> (3)
  *   M Nodejs/Prerequisites/DisableSkipVerificationX86.reg<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-3> (1)
  *   M Nodejs/Prerequisites/EnableSkipVerification.reg<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-4> (3)
  *   M Nodejs/Prerequisites/EnableSkipVerificationX86.reg<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-5> (1)
  *   M Nodejs/Prerequisites/generate.js<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-6> (3)
  *   M Nodejs/Product/Nodejs/Nodejs.csproj<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-7> (8)
  *   M Nodejs/Product/Nodejs/NodejsPackage.cs<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-8> (29)
  *   M Nodejs/Product/Nodejs/Project/ImportWizard/ImportSettings.cs<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-9> (12)
  *   M Nodejs/Product/Nodejs/source.extension.vsixmanifest<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-10> (1)
  *   A Nodejs/Product/Telemetry/DefaultImpl/DefaultTelemetryFactory.cs<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-11> (35)
  *   A Nodejs/Product/Telemetry/DefaultImpl/DefaultTelemetryLogger.cs<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-12> (52)
  *   A Nodejs/Product/Telemetry/Properties/AssemblyInfo.cs<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-13> (31)
  *   A Nodejs/Product/Telemetry/Shared/DataPoint.cs<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-14> (35)
  *   A Nodejs/Product/Telemetry/Shared/DataPointCollection.cs<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-15> (34)
  *   A Nodejs/Product/Telemetry/Shared/ITelemetryFactory.cs<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-16> (27)
  *   A Nodejs/Product/Telemetry/Shared/ITelemetryLogger.cs<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-17> (53)
  *   A Nodejs/Product/Telemetry/Telemetry.csproj<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-18> (106)
  *   A Nodejs/Product/Telemetry/TelemetryEvents.cs<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-19> (27)
  *   A Nodejs/Product/Telemetry/TelemetryProperties.cs<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-20> (28)
  *   A Nodejs/Product/Telemetry/TelemetrySetup.cs<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-21> (70)
  *   M Nodejs/Setup/BuildRelease.ps1<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-22> (3)
  *   M Nodejs/Setup/NodejsTools/NodejsToolsFiles.proj<https://github.com/ryan-dawson/nodejstools/pull/1/files#diff-23> (1)

Patch Links:

  *   https://github.com/ryan-dawson/nodejstools/pull/1.patch
  *   https://github.com/ryan-dawson/nodejstools/pull/1.diff

**Comment by nareshjo** [comment]
Ryan wanted it to be pulled to his personal branch first. Probably as a precaution to not break anything in microsoft/nodejstools as we are relatively new to git.

**Comment by ryan-dawson** [comment]
Please move the Telemetry project under the Product folder in the main solution.  It looks odd being the one and only top level project and under Product is probably the right place for it.

**Comment by nareshjo** [comment]
It was supposed to be there only. Not sure how it got out. Moved it back.

**Comment by nareshjo** [comment]
Remove SetSharedProperty methods as they have been replaced by SetCommonProperty

**Pull request closed without merging**
